name: distra_aft
description: "Aplicación móvil offline-first para conteo de Activos Fijos Tangibles (AFT) integrada con DISTRA ERP."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  go_router: ^14.7.2
  isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  tree_view_flutter: ^1.0.2
  flutter_riverpod: ^2.5.1
  # sqflite: 2.0.0
  path: ^1.8.3
  objectbox: ^4.3.0
  # flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
